- alias: Send a notification when the doorbell is pressed
  description: ''
  trigger:
  - platform: state
    entity_id: switch.aeon_labs_zw056_doorbell_gen5_switch
    to: 'on'
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: Someone is at the door!
  - service: tts.google_translate_say
    entity_id:
    - media_player.living_room
    - media_player.master_bedroom_speaker
    data:
      message: Someone is at the door!
  mode: single
  id: a3e5777c438b4dfaa2a4a25ef230c730
- alias: Location Tracking
  description: Tracks our location
  trigger:
  - platform: state
    entity_id:
    - person.alec_down
    - person.kelsey_down
    - person.christopher_hansen
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition:
  - condition: template
    value_template: '{{  trigger.from_state.state != trigger.to_state.state }}'
  # - condition: template
  #   value_template: "{{ ( (as_timestamp(now()) - (5 * 3600)) - as_timestamp(trigger.to_state.last_changed)) > 180 }}"
  action:
  - service: notify.notify
    data_template:
      message: '{{ trigger.to_state.attributes.friendly_name }} {% if trigger.to_state.state
        == ''not_home'' %}has left {{ trigger.from_state.state }}{% endif %}{% if
        trigger.from_state.state == ''not_home'' %}arrived at {{ trigger.to_state.state
        }}{% endif %}.'
  mode: single
  id: 27204060374d4aefbf8e5a4a199685b2
# - alias: Run Noodle when everyone is away
#   description: ''
#   trigger:
#   - platform: state
#     entity_id: group.people
#     to: not_home
#   condition:
#   - condition: template
#     value_template: '{{as_timestamp(state_attr(''automation.run_noodle_when_everyone_is_away'',''last_triggered''))|timestamp_custom(''%-d'')
#       != as_timestamp(now())|timestamp_custom(''%-d'')}}'
#   action:
#   - service: vacuum.start
#     data: {}
#     entity_id: vacuum.noodle
#   - service: notify.notify
#     data_template:
#       message: Noodle has started vacuuming.
#   mode: single
#   id: 36cffed45afd4779991fc97c6334f5b6
- alias: Unlock door when someone arrives home
  description: ''
  trigger:
  - platform: zone
    entity_id:
    - person.alec_down
    - person.kelsey_down
    - person.christopher_hansen
    zone: zone.home
    event: enter
  condition: []
  action:
  - device_id: 5f5d09fdfb4611ea9bcab11affd24be8
    domain: lock
    entity_id: lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
    type: unlock
  mode: single
  id: 5fb56f6384af4dafbeb7c0e22ec9899d
- alias: Turn all lights off when everyone is away
  description: ''
  trigger:
  - platform: state
    entity_id: group.people
    to: not_home
  condition: []
  action:
  - service: light.turn_off
    entity_id: all
  mode: single
  id: ef464d38b3c041578b6fba3dc02dabc5
- alias: Charlie's lights turn off at 20:00
  description: ''
  trigger:
  - platform: time
    at: '20:00:00'
  condition: []
  action:
  - domain: light
    entity_id: light.charlie_s_room_main
    device_id: b5903047f9dd11ea8b6a49751688ce3d
    type: turn_off
  - domain: light
    entity_id: light.charlie_s_lamp
    device_id: b593abebf9dd11ea8be8175731296711
    type: turn_off
  id: 7efb421015344e71a426b8c6b95ba71d
- alias: Brighten lights in the morning
  description: ''
  trigger:
  - platform: time
    at: 08:00:00
  condition: []
  action:
  - service: script.turn_on
    entity_id:
    - script.morning_lights
  mode: single
  id: d7b7dbe11c68434e8f687dae16e527b3
- alias: Dim lights in the evening
  description: ''
  trigger:
  - platform: time
    at: '19:00:00'
  condition: []
  action:
  - service: script.turn_on
    entity_id:
    - script.evening_lights
  mode: single
  id: 4695291fc7e94175a08796877028eba5
- alias: Set lights to 100% if turned on during the day
  description: ''
  trigger:
    platform: state
    entity_id:
    - light.office
    - light.kitchen_zha_group_0x0003
    - light.dining_room_zha_group_0x0002
    - light.living_room_zha_group_0x0004
    - light.entryway_zha_group_0x0005
    - light.hallway
    - light.charlie_s_bathroom
    - light.charlie_s_lamp
    - light.charlie_s_room_main
    - light.guest_bathroom
    - light.master_bedroom_zha_group_0x0006
    - light.landing_zha_group_0x0007
    to: 'on'
  condition:
    condition: time
    after: 06:00
    before: '19:00'
  action:
    service: light.turn_on
    data_template:
      entity_id: '{{ trigger.entity_id }}'
      brightness: 255
  mode: single
  id: ac1533507f944e0aa9d1776b9256a8dd
- alias: Dim if turned on after 7pm
  description: ''
  trigger:
    platform: state
    entity_id:
    - light.office
    - light.kitchen_zha_group_0x0003
    - light.dining_room_zha_group_0x0002
    - light.living_room_zha_group_0x0004
    - light.entryway_zha_group_0x0005
    - light.hallway
    - light.charlie_s_bathroom
    - light.charlie_s_lamp
    - light.charlie_s_room_main
    - light.guest_bathroom
    - light.master_bedroom_zha_group_0x0006
    - light.landing_zha_group_0x0007
    to: 'on'
  condition:
    condition: time
    after: '19:00'
    before: 06:00
  action:
    service: light.turn_on
    data_template:
      entity_id: '{{ trigger.entity_id }}'
      brightness: 50
  mode: single
  id: 2758ef69c73e4556a69740dd619dd287
- alias: Turn off Charlie's lights if turned on after 8pm
  description: ''
  trigger:
    platform: state
    entity_id:
    - light.charlie_s_lamp
    - light.charlie_s_room_main
    to: 'on'
  condition:
    condition: time
    after: '20:00'
    before: 05:00
  action:
    service: light.turn_off
    data_template:
      entity_id: '{{ trigger.entity_id }}'
  mode: single
  id: ebaf819ae9474d22bb59bf1367eb82ce
- alias: Lock the door after 5 minutes
  description: ''
  trigger:
  - platform: device
    device_id: 5f5d09fdfb4611ea9bcab11affd24be8
    domain: lock
    entity_id: lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
    type: unlocked
  condition: []
  action:
  - delay:
      minutes: 5
  - device_id: 5f5d09fdfb4611ea9bcab11affd24be8
    domain: lock
    entity_id: lock.schlage_allegion_be469zp_connect_smart_deadbolt_locked
    type: lock
  mode: single
  id: fe76cbb261f34a7fae81587d5cd6bbd9
- alias: Set theme at startup
  trigger:
    platform: homeassistant
    event: start
  action:
    service: frontend.set_theme
    data:
      name: iOS Light Mode
  id: 2ea026ccab3342fe84c4149f9c9255f8
- alias: Set HA theme for day and night
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  action:
  - service: frontend.set_theme
    data_template:
      name: "{% if states.sun.sun.state == \"above_horizon\" %}\n  iOS Light Mode\n\
        {% else %}\n  iOS Dark Mode\n{% endif %}\n"
  id: 5bf99640607c437ab0f1045291a45607
- alias: Kitchen sink leak notification
  description: ''
  trigger:
    - platform: state
      entity_id: binary_sensor.water_sensor_1_ias_zone
      to: 'on'
      for:
        hours: 0
        minutes: 0
        seconds: 5
  condition: []
  action:
  - service: notify.notify
    data_template:
      message: Kitchen leak sensor is wet!
  mode: single
- alias: Alert for waste day
  description: ''
  trigger:
    - platform: time
      at: '18:00:00'
  condition: 
    condition: state
    entity_id: sensor.waste
    state: '1'
  action:
    - service: notify.notify
      data_template:
        message: Hey folks, tomorrow is trash day! 
- alias: Alert for recycling day
  description: ''
  trigger:
    - platform: time
      at: '18:00:00'
  condition: 
    condition: state
    entity_id: sensor.recycling
    state: '1'
  action:
    - service: notify.notify
      data_template:
        message: Hey folks, tomorrow is recycling day! 
- alias: Trash day
  description: ''
  trigger:
    - platform: time
      at: '06:45:00'
  condition: 
    condition: state
    entity_id: sensor.waste
    state: '0'
  action:
    - service: notify.notify
      data_template:
        message: Get that trash out!
    - service: tts.google_translate_say
      entity_id:
        - media_player.living_room
        - media_player.master_bedroom_speaker
      data:
        message: Trash cans need to be out in 15 minutes!

