# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# SSDP
ssdp:

# Local input_boolean
local_ip:

# Enable themes
frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
# themes: !include themes.yaml
